{% set name = "napari-mclabel" %}
{% set version = "1.0.1.dev0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-mclabel-{{ version }}.tar.gz
  sha256: c6e24a061e33378eada2c13e5aa416ace5d2658392c2ec679fcf3927ccab49c9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools-scm
    - pip
  run:
    - python >=3.8
    - napari
    - napari-plugin-engine >=0.1.4
    - imaris-ims-file-reader >=0.1.5
    - numpy
    - h5py
    - dask-core
    - napari-imaris-loader
    - scikit-image
    - scipy

test:
  imports:
    - napari_mclabel
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt

about:
  home: https://pypi.org/project/napari-mclabel
  summary: Napari plugin for semi-automatic labeling of macrophages
  license: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/jonasutz/mclabel

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - jonasutz
